/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robot_k-vrc.glb -T -s 
Files: public/robot_k-vrc.glb [42.11MB] > /Users/renoroy/Downloads/app 2/robot_k-vrc-transformed.glb [511.31KB] (99%)
Author: VolDeMaar (Padawan 3D) (https://sketchfab.com/Padawan3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-k-vrc-11ca2a59002b4c64986b44e46f389b47
Title: Robot K-VRC
*/

import { useGLTF } from '@react-three/drei'

export default function Robot(props: any) {
  const { nodes, materials } = useGLTF('/robot_k-vrc-transformed.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['LDR_Bot001_TT_material_override-LDR_Bot001_0'].geometry} material={materials['TT_material_override-LDR_Bot.001']} position={[-0.016, -0.006, -0.064]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/robot_k-vrc-transformed.glb')
